global using AdaptiveTestingSystem.UserLibraly;
global using AdaptiveTestingSystem.DLL.CScript;
global using static AdaptiveTestingSystem.Data.Enums;
global using static AdaptiveTestingSystem.DLL.CScript.ControlEnum;
global using AdaptiveTestingSystem.Data.JsonData;
global using AdaptiveTestingSystem.Control.CustomControl;
global using AdaptiveTestingSystem.Control.Themes;
global using AdaptiveTestingSystem.UserApplication.Assets.View;
global using AdaptiveTestingSystem.MVVMLibraly;
global using AdaptiveTestingSystem.UserApplication.Assets.MVVM.Model;
global using AdaptiveTestingSystem.Control.Windows;
global using AdaptiveTestingSystem.UserApplication.Assets.CScript;
global using AdaptiveTestingSystem.UserApplication;
global using AdaptiveTestingSystem.UserApplication.Assets.Command;
global using AdaptiveTestingSystem.UserApplication.Client;
global using AdaptiveTestingSystem.UserApplication.Assets.GUI;
global using AdaptiveTestingSystem.UserApplication.Assets.MVVM.ViewModel;
global using AdaptiveTestingSystem.UserApplication.Assets.MVVM;
global using static AdaptiveTestingSystem.UserApplication.Assets.CScript.StructList;
global using System.Text.Json;
global using System.Windows;
